### ISSUE TITLE
現在の起動時にターミナル側のコンソールにエラーが出るが、なんのエラーかわからない

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#1007]
## 不具合の内容

現在のmainで起動時にコンソール（ターミナル側）にエラーが出るのですが、なぜこのエラーが出ているかわからずにいます。
特に問題なく動いているのですが、なにか変なバグの原因になるかもしれないので、調べておきたいです。

エラーの発生箇所を突き止めて、なぜこのエラーが出るのかわかりやすいメッセージを表示したいです。
（DefaultApi辺りのログが出ているので、エンジン周り･･･？）

### 現象・ログ

起動時にこんな感じのエラーが出ます。

```
[25296:1104/052150.927:ERROR:CONSOLE(160)] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: node:electron/js2c/sandbox_bundle (160)
[05:21:52.798] [error] TypeError: Failed to fetch
    at DefaultApi._callee$ (http://localhost:8080/js/webpack:/src/openapi/runtime.ts:89:30)
    at tryCatch (http://localhost:8080/js/webpack:/node_modules/regenerator-runtime/runtime.js:63:15)
    at Generator.invoke [as _invoke] (http://localhost:8080/js/webpack:/node_modules/regenerator-runtime/runtime.js:293:1)
    at Generator.next (http://localhost:8080/js/webpack:/node_modules/regenerator-runtime/runtime.js:118:1)
    at http://localhost:8080/js/webpack:/node_modules/tslib/tslib.es6.js:74:1
    at new Promise (<anonymous>)
    at __awaiter (http://localhost:8080/js/webpack:/node_modules/tslib/tslib.es6.js:70:1)
    at DefaultApi.BaseAPI.fetchApi (http://localhost:8080/js/webpack:/src/openapi/runtime.ts:79:65)
    at DefaultApi._callee2$ (http://localhost:8080/js/webpack:/src/openapi/runtime.ts:49:37)
    at tryCatch (http://localhost:8080/js/webpack:/node_modules/regenerator-runtime/runtime.js:63:15)
```

### 再現手順

f8d44344606f889cec11dfc04243f9d11de10e07 で起動すると出る

### 期待動作

エラーが出ない、あるいはエラー内容がわかりやすいエラーメッセージが表示される

## その他

（自分とこ以外の環境では出ない･･･？）

**Comment by jdkfx** [comment]
これって https://github.com/VOICEVOX/voicevox/commit/f8d44344606f889cec11dfc04243f9d11de10e07 当時の開発環境と今の開発環境が全く違うものになり、調査も難しいのでクローズでも良さそうかなと思いました。

**Comment by jdkfx** [comment]
と思ったんですけど、現状のmain https://github.com/VOICEVOX/voicevox/commit/4233089aca57551d06534193248a3a87f60d5c6e で起動した際にターミナル上でエラー起きてました。

```
[12131:1216/000554.711556:ERROR:CONSOLE(1)] "Unknown VE context: language-mismatch    at new He (devtools://devtools/bundled/ui/legacy/legacy.js:1:98356)
    at devtools://devtools/bundled/ui/legacy/legacy.js:1:191793
    at new oi (devtools://devtools/bundled/ui/legacy/legacy.js:1:192189)
    at oi.instance (devtools://devtools/bundled/ui/legacy/legacy.js:1:192311)
    at O.presentUI (devtools://devtools/bundled/panels/emulation/emulation.js:1:58454)
    at #I (devtools://devtools/bundled/entrypoints/main/main.js:1:17314)
    at #x (devtools://devtools/bundled/entrypoints/main/main.js:1:17109)", source: devtools://devtools/bundled/ui/visual_logging/visual_logging.js (1)
[12131:1216/000557.055136:ERROR:CONSOLE(2)] "Electron renderer.bundle.js script failed to run", source: node:electron/js2c/renderer_init (2)
[12131:1216/000557.055200:ERROR:CONSOLE(2)] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: node:electron/js2c/renderer_init (2)
[12131:1216/000600.621581:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
[12131:1216/000600.622111:ERROR:CONSOLE(1)] "Request Autofill.setAddresses failed. {"code":-32601,"message":"'Autofill.setAddresses' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
```

どう関係あるのかはよく分かってない...

**Comment by Hiroshiba** [comment]
コメントありがとうございます、いつも助かってます！！！！

こちらでも確認してみました！
↓こっちのログは出てましたが、
```
TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: node:electron/js2c/sandbox_bundle (160)
```
VOICEVOX内のコードっぽい`DefaultApi`が絡む↓こっちのログが出てないことを確認しました！
```
[error] TypeError: Failed to fetch
```

僕の方でも確認できなくなってしまっているので、このissueはクローズで良さそうに思いました！

Chromium周りっぽいエラー？ワーニング？のログが出てますが、まあこれはよくわからないので放置で良さそう！！
ということでクローズしたいと思います！　ありがとうございました！！
