### ISSUE TITLE
ユーザー辞書に登録しようとすると辞書ファイルが壊れる

### ISSUE THREAD

**Issue by okaits** [VOICEVOX/voicevox#1054]
## 不具合の内容
UIからユーザー辞書に単語を追加しようとすると、エラーが発生して、それ以降起動処理に失敗してしまいます。

### 現象・ログ
登録時のログ (前後に関係ありそうな情報がなかったので一部のみ)
```
[03:16:53.514] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDOUT: INFO:     127.0.0.1:53534 - "POST /user_dict_word?surface=%EF%BC%A7%EF%BD%89%EF%BD%94%EF%BC%A8%EF%BD%95%EF%BD%82&pronunciation=%E3%82%AE%E3%83%83%E3%83%88%E3%83%8F%E3%83%96&accent_type=1&priority=5 HTTP/1.1" 422 Unprocessable Entity
```

登録しようとしてからもう一度起動しようとした時のログ
```
[03:18:00.043] [info]  Starting 1 engine/s...
[03:18:00.046] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d: Start launching
[03:18:00.046] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d: Starting process
[03:18:00.051] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d mode: GPU
[03:18:00.051] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d path: /tmp/.mount_VOICEV25g4eu/run
[03:18:00.051] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d args: ["--use_gpu"]
[03:18:03.435] [error] ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDERR: Warning: cpu_num_threads is set to 0. ( The library leaves the decision to the synthesis runtime )

[03:18:03.453] [error] ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDERR: INFO:     Started server process [451652]
INFO:     Waiting for application startup.

[03:18:03.458] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDOUT: reading /tmp/.mount_VOICEV25g4eu/default.csv ... 45
emitting double-array: 100% |###########################################| 

[03:18:03.462] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDOUT: 
done!
reading /tmp/tmp5j3oaw7m ... 47
emitting double-array:  39% |################                           | 
emitting double-array: 100% |###########################################|  emitting double-array:  41% |#################                          | 

[03:18:03.467] [error] ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDERR: ERROR:    Traceback (most recent call last):
  File "/tmp/.mount_VOICEV25g4eu/starlette/routing.py", line 621, in lifespan
  File "/tmp/.mount_VOICEV25g4eu/starlette/routing.py", line 518, in __aenter__
  File "/tmp/.mount_VOICEV25g4eu/starlette/routing.py", line 600, in startup
  File "/tmp/.mount_VOICEV25g4eu/run.py", line 114, in apply_user_dict
  File "/tmp/.mount_VOICEV25g4eu/voicevox_engine/user_dict.py", line 54, in user_dict_startup_processing
  File "/tmp/.mount_VOICEV25g4eu/voicevox_engine/user_dict.py", line 108, in update_dict
  File "/tmp/.mount_VOICEV25g4eu/pathlib.py", line 1374, in replace
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmplvepr6al' -> '/home/okaits/.local/share/voicevox-engine/user.dic'

ERROR:    Application startup failed. Exiting.

[03:18:03.480] [info]  Waiting engine 074fc39e-678b-4c13-8916-ffca8d505d1d
[03:18:03.543] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDOUT: 
done!

[03:18:03.713] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d: Process terminated due to receipt of signal null
[03:18:03.713] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d: Process exited with code 0
[03:18:05.173] [info]  Waiting engine 074fc39e-678b-4c13-8916-ffca8d505d1d
[03:18:05.175] [error] Error: Failed to fetch Failed to get speakers.
[03:18:05.176] [error] TypeError: Failed to fetch
    at Ae.next (app://./js/webpack:/src/openapi/runtime.ts:89:62)
    at Generator.next (<anonymous>)
    at app://./js/webpack:/node_modules/tslib/tslib.es6.js:74:71
    at new Promise (<anonymous>)
    at o (app://./js/webpack:/node_modules/tslib/tslib.es6.js:70:12)
    at Ae.fetchApi (app://./js/webpack:/src/openapi/runtime.ts:79:65)
    at Ae.next (app://./js/webpack:/src/openapi/runtime.ts:49:37)
    at Generator.next (<anonymous>)
    at app://./js/webpack:/node_modules/tslib/tslib.es6.js:74:71
    at new Promise (<anonymous>)
[03:18:06.452] [info]  All windows closed. Quitting app
[03:18:06.452] [info]  Checking ENGINE status before app quit
[03:18:06.453] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d: last exit code: 0, signal: null
[03:18:06.453] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d: Process already closed
[03:18:06.453] [info]  All ENGINE processes killed. Now quit app

```

### 再現手順
1. VOICEVOX公式サイトからインストーラスクリプトをダウンロードし、一般ユーザ権限で実行する
2. インストールが完了してから、実行する
3. 起動完了後、メニューバーから、設定→読み方＆アクセント辞書を開く
4. GitHubという単語（読み: ギットハブ、アクセント: 一番最初、優先度: 5）を登録しようとする
5. エラーが出る
6. 一度VOICEVOXを閉じる
7. もう一度VOICEVOXを開こうとしても、エラーが発生して開かない

### 期待動作
辞書に単語が登録される

## VOICEVOXのバージョン

0.13.3 (GPU版)

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [x] Linux

* Ubuntu 22.10 (amd64)
* Linux 6.1.0-rc7+
* ルートファイルシステム: btrfs

## その他
* 辞書登録に失敗して、起動しなくなった後、`rm -r ~/.local/share/voicevox-engine`を実行すると、正常に起動する
* エンジンのAPIを直接叩いても、同じ不具合が発生する

**Comment by okaits** [comment]
単語登録時のスクリーンショットです。
![Screenshot from 2022-12-18 03-17-04](https://user-images.githubusercontent.com/48373501/208256538-f63da717-b05f-4b52-ae88-3bf49636c6cc.png)
