### ISSUE TITLE
テキスト欄の削除のショートカットが効かない

### ISSUE THREAD

**Issue by wappon-28-dev** [VOICEVOX/voicevox#1268]
## 不具合の内容

テキスト欄の削除のショートカット(デフォ: Shift + Delete) が効かない

### 現象・ログ

</details>
<details><summary>20230401_014013_error.log</summary>
<pre>
[01:40:14.717] [error] ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDERR: 2023-03-31T16:40:14.718081Z  INFO voicevox_core::publish: 検出されたGPU (DirectMLには1番目のGPUが使われます):

[01:40:14.724] [error] ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDERR: 2023-03-31T16:40:14.724884Z  INFO voicevox_core::publish:   - "Intel(R) UHD Graphics 630" (128 MiB)
2023-03-31T16:40:14.724919Z  INFO voicevox_core::publish:   - "Microsoft Basic Render Driver" (0 B)

[01:40:16.042] [error] ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDERR: Warning: cpu_num_threads is set to 0. ( The library leaves the decision to the synthesis runtime )

[01:40:16.082] [error] ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDERR: INFO:     Started server process [1840]
INFO:     Waiting for application startup.

[01:40:16.164] [error] ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDERR: ERROR:    Application startup failed. Exiting.

[01:40:23.507] [error] TypeError: D[L.value].removeCell is not a function
    at next (app://./js/webpack:/src/views/EditorHome.vue?dde2:102:43)
    at Generator.next (<anonymous>)
    at app://./js/webpack:/node_modules/tslib/tslib.es6.js:74:71
    at new Promise (<anonymous>)
    at o (app://./js/webpack:/node_modules/tslib/tslib.es6.js:70:12)
    at removeAudioItem (app://./js/webpack:/src/views/EditorHome.vue?dde2:100:40)
    at HTMLDocument.<anonymous> (app://./js/webpack:/src/views/EditorHome.vue?dde2:132:11)
[01:40:23.966] [error] TypeError: D[L.value].removeCell is not a function
    at next (app://./js/webpack:/src/views/EditorHome.vue?dde2:102:43)
    at Generator.next (<anonymous>)
    at app://./js/webpack:/node_modules/tslib/tslib.es6.js:74:71
    at new Promise (<anonymous>)
    at o (app://./js/webpack:/node_modules/tslib/tslib.es6.js:70:12)
    at removeAudioItem (app://./js/webpack:/src/views/EditorHome.vue?dde2:100:40)
    at HTMLDocument.<anonymous> (app://./js/webpack:/src/views/EditorHome.vue?dde2:132:11)
</pre>
</details> 

<details><summary>on_main_branch_error.log</summary>
<pre>
-------------------------------------------------------------------------------------------------
preload.ts:195 
TypeError: audioCellRefs[activeAudioKey.value].removeCell is not a function
    at removeAudioItem (EditorHome.vue:244:39)
    at HTMLDocument.<anonymous> (EditorHome.vue:274:7)

logError @ preload.ts:195
action @ index.ts:307
wrappedActionHandler @ vuex.esm-bundler.js:305
dispatch @ vuex.esm-bundler.js:1032
boundDispatch @ vuex.esm-bundler.js:914
logError @ ErrorBoundary.vue:11
handlePromiseRejectionEvent @ ErrorBoundary.vue:18

-------------------------------------------------------------------------------------------------
EditorHome.vue:244
Uncaught (in promise) TypeError: audioCellRefs[activeAudioKey.value].removeCell is not a function
    at removeAudioItem (EditorHome.vue:244:39)
    at HTMLDocument.<anonymous> (EditorHome.vue:274:7)

removeAudioItem @ EditorHome.vue:244
(anonymous) @ EditorHome.vue:274
</pre>
</details> 

### 再現手順
1. VOICEVOXを起動する
2. １回以上改行する
3. テキスト欄の削除のショートカットを押す (デフォ: Shift + Delete)

https://user-images.githubusercontent.com/86721991/229184306-5f984db3-5747-4eaa-966d-c2d9e7737a77.mp4

### 期待動作
正常にテキスト欄が削除できる

## VOICEVOXのバージョン

v0.14.5 & v0.14.6

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS ?
- [ ] Linux ?

Windows 11 Pro (22621.1485)

## その他

- もしかして: https://twitter.com/febbccc/status/1639353355238768640
- v0.13.3 では正常に動いたそうです (境界かどうかは分かりませんが)

**Comment by raa0121** [comment]
AudioCell.vue を `<script setup lang="ts">` するようにした結果、関数の巻き上げがされてないんじゃないかと思います。
