### ISSUE TITLE
初回起動したエンジンが異常終了したときにエラーダイアログが表示されない

### ISSUE THREAD

**Issue by sabonerune** [VOICEVOX/voicevox#1349]
## 不具合の内容

初回起動したエンジンが異常終了したときエラーダイアログが表示されません。
一度エンジンを再起動させた後に異常終了した場合はダイアログが表示されます。

恐らく ccf3ff069468151369fdd34ca59e61e8453a13d5 で`BrowserWindow`を作成する前にエンジンを起動するようにしてしまったためイベントハンドラに渡す`win`が`undefined`になってしまったことが原因だと思います。

https://github.com/VOICEVOX/voicevox/blob/34f82d6679d842d280a12997b41627ce6b8d82b6/src/background.ts#L542-L543
https://github.com/VOICEVOX/voicevox/blob/34f82d6679d842d280a12997b41627ce6b8d82b6/src/background/engineManager.ts#L332-L346

### 現象・ログ

```
[23:10:19.593] [error] TypeError: Cannot read properties of undefined (reading 'webContents')
    at Hu (D:\Dev\voicevox\dist\background.js:415:513)
    at ChildProcess.<anonymous> (D:\Dev\voicevox\dist\background.js:415:4893)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
    at Process.callbackTrampoline (node:internal/async_hooks:130:17)
```

### 再現手順

エディタ起動完了後タスクマネージャー等でエンジンを強制終了する。

### 期待動作

エンジンが異常終了したときエラーダイアログが表示される。

## VOICEVOXのバージョン

ccf3ff069468151369fdd34ca59e61e8453a13d5 以降

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

## その他

恐らく全てのプラットフォームで発生。

**Comment by Hiroshiba** [comment]
ありがとうございます！！

いろいろ解決策がありそうですが、そもそもEngineManagerが`win`を引数に受け取っていることが問題に思いました。

winを使うのは`ipcMainSend(win, "DETECTED_ENGINE_ERROR", { engineId });`を実行するためっぽいです。
エラーが起きたらコールバックする`onError`引数を作り、そのコールバック内で↑を実行する形にするのが良いのかなと思いました。
ちょっとPR作ってみます！
