### ISSUE TITLE
マルチトラック：ノートの複数選択ができない

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#2183]
## 不具合の内容

マルチトラックプロジェクトブランチでのバグメモです。

マルチトラックをオンにしていてもオフにしていてもノートの複数選択ができない気がします。

### 現象・ログ

```log
VM5:4181 Error: draggingNote is undefined.
logError @ VM5:4181
logError @ ErrorBoundary.vue:9
(anonymous) @ ErrorBoundary.vue:24
ScoreSequencer.vue:462 Uncaught Error: draggingNote is undefined.
    at previewMove (ScoreSequencer.vue:462:11)
    at preview (ScoreSequencer.vue:707:7)
```

### 再現手順

ノート2つ配置する。
片方をクリックする。
もう片方をshiftを押しながらクリックする。
もしくはctrlを押しながらクリックでも。

## VOICEVOXのバージョン

`project-multitrack` 2c87e5ed7ffca1405a65f97f31b0c25a229669dc

## その他

たぶん現メインブランチでは問題なさそう。
shift+ドラッグは問題なさそう。

バグはあるけれどもとりあえずmainブランチにマージしたい気持ちがあります。
（ちょっととある理由で可能なら月末までにリリースしたく、mainマージも含めてデバッグしたいため）

**Comment by Hiroshiba** [comment]
自動closeされてなかったのでclose！
