### ISSUE TITLE
ESLintを最新にしてFlat Configにする

### ISSUE THREAD

**Issue by MT224244** [VOICEVOX/voicevox#2216]
## 内容

現在最新のeslint@v9ではデフォルトがFlat Configになり、v10では旧コンフィグが廃止される予定のようです。  
https://eslint.org/blog/2023/10/flat-config-rollout-plans/

### Pros 良くなる点

[ESLint Config Inspector](https://github.com/eslint/config-inspector)というツールが使えるようになり、適用されている設定の確認が非常に簡単になります。

### Cons 悪くなる点

特になし？

### 実現方法

1. eslint周りの依存関係を最新にする
1. `.eslintrc.js` を削除し、 `eslint.config.mjs` を作る

試しにできる限り対応してみたブランチが[こちら](https://github.com/MT224244/voicevox/tree/flat-config)。

~~`@vue/eslint-config-typescript` を強制インストールしているので、 `npm i --force` する必要があります。~~  
~~`eslint-plugin-storybook` は無効化してあります。~~  
~~後述している3件+2件で合計5件のエラーが残っている状態です。~~

<details>
<summary>npm run lint (obsolete)</summary>

```
path\to\voicevox\src\backend\browser\fileImpl.ts
  24:7  error  Expected the Promise rejection reason to be an Error  @typescript-eslint/prefer-promise-reject-errors
  40:9  error  Expected the Promise rejection reason to be an Error  @typescript-eslint/prefer-promise-reject-errors

path\to\voicevox\src\store\audio.ts
  1534:17  error  Expected the Promise rejection reason to be an Error  @typescript-eslint/prefer-promise-reject-errors

path\to\voicevox\src\store\audioContinuousPlayer.ts
  37:7   error  Avoid referencing unbound methods which may cause unintentional scoping of `this`.
If your function does not access `this`, you can annotate it with `this: void`, or consider using an arrow function instead  @typescript-eslint/unbound-method
  37:22  error  Avoid referencing unbound methods which may cause unintentional scoping of `this`.
If your function does not access `this`, you can annotate it with `this: void`, or consider using an arrow function instead  @typescript-eslint/unbound-method

✖ 5 problems (5 errors, 0 warnings)
```
</details>

Issue作成当時未対応だったプラグインも既に全て対応完了していたので、上記ブランチもそれに合わせて更新しました。

~~#2379 の影響で `import/order` だけ有効化できない状態ですが、それ以外は(おそらく)正常に動作しています。~~
こちらも解決したようです。

<details>
<summary>pnpm lint</summary>

```
path/to/voicevox/src/backend/browser/fileImpl.ts
  25:7  error  Expected the Promise rejection reason to be an Error  @typescript-eslint/prefer-promise-reject-errors
  41:9  error  Expected the Promise rejection reason to be an Error  @typescript-eslint/prefer-promise-reject-errors

path/to/voicevox/src/backend/browser/sandbox.ts
  71:7  error  Unsafe return of a value of type `Promise<any>`  @typescript-eslint/no-unsafe-return

path/to/voicevox/src/backend/electron/manager/engineInfoManager.ts
  239:14  warning  'e' is defined but never used  @typescript-eslint/no-unused-vars

path/to/voicevox/src/backend/electron/manager/windowManager.ts
  125:7  error  Expected an assignment or function call and instead saw an expression  @typescript-eslint/no-unused-expressions

path/to/voicevox/src/components/Dialog/CharacterOrderDialog.vue
  91:21  error  Replace `··selectCharacterWithChangePortrait(⏎························element.metas.speakerUuid,⏎······················` with `selectCharacterWithChangePortrait(element.metas.speakerUuid`  prettier/prettier

path/to/voicevox/src/components/Dialog/SettingDialog/SettingDialog.vue
  221:19  error  Attribute 'v-model:open-dialog' can't be hyphenated  vue/attribute-hyphenation
  239:19  error  Attribute 'v-model:open-dialog' can't be hyphenated  vue/attribute-hyphenation

path/to/voicevox/src/components/Menu/ContextMenu/Presentation.vue
  41:31  error  Explicit undefined is unnecessary on an optional parameter  @typescript-eslint/no-duplicate-type-constituents

path/to/voicevox/src/components/Menu/MenuButton.vue
  11:7  error  Delete `··`  prettier/prettier

path/to/voicevox/src/components/Sing/ToolBar/ToolBar.vue
  508:3  error  Delete `··`               prettier/prettier
  509:1  error  Replace `····` with `··`  prettier/prettier
  510:1  error  Delete `··`               prettier/prettier

path/to/voicevox/src/components/Talk/AudioCell.vue
  48:7  error  Attribute 'v-model:selected-voice' can't be hyphenated  vue/attribute-hyphenation

path/to/voicevox/src/components/Talk/AudioInfo.vue
   86:27  error  Attribute 'v-model:open-dialog' can't be hyphenated     vue/attribute-hyphenation
  219:11  error  Attribute 'v-model:selected-voice' can't be hyphenated  vue/attribute-hyphenation

path/to/voicevox/src/store/audio.ts
  1553:30  error  'reader.result' may use Object's default stringification format ('[object Object]') when stringified  @typescript-eslint/no-base-to-string
  1558:17  error  Expected the Promise rejection reason to be an Error                                                  @typescript-eslint/prefer-promise-reject-errors

path/to/voicevox/src/store/audioContinuousPlayer.ts
  37:7   error  Avoid referencing unbound methods which may cause unintentional scoping of `this`.
If your function does not access `this`, you can annotate it with `this: void`, or consider using an arrow function instead  @typescript-eslint/unbound-method
  37:22  error  Avoid referencing unbound methods which may cause unintentional scoping of `this`.
If your function does not access `this`, you can annotate it with `this: void`, or consider using an arrow function instead  @typescript-eslint/unbound-method

path/to/voicevox/src/type/preload.ts
  500:48  error  Explicit undefined is unnecessary on an optional parameter  @typescript-eslint/no-duplicate-type-constituents

path/to/voicevox/tools/generateLicenses.mts
  63:32  error  Replace `⏎··import.meta.dirname,⏎··"..",⏎··"vendored",⏎··"7z",⏎` with `import.meta.dirname,·"..",·"vendored",·"7z"`  prettier/prettier

✖ 22 problems (21 errors, 1 warning)
  13 errors and 0 warnings potentially fixable with the `--fix` option.
```
</details>

#### ルール `@typescript-eslint/ban-types` について

このルールは廃止され、4つのルールに分割されたようです。  
https://typescript-eslint.io/rules/ban-types/

- `no-restricted-types`
- `no-empty-object-type`
- `no-unsafe-function-type`
- `no-wrapper-object-types`

このルールを無効化している箇所のdisableコメントを書き換える必要があります。  
これは議論の余地があるかもしれませんが、 `no-empty-object-type` はoffで良いのではと思っています。

#### ルール `@typescript-eslint/no-require-imports` について

[ルールの名前が変わった](https://typescript-eslint.io/rules/no-var-requires/)ようです。 `no-var-requires` -> `no-require-imports`  
このルールを無効化している箇所のdisableコメントを書き換える必要があります。

#### ルール `@typescript-eslint/prefer-promise-reject-errors` について

FlatConfigに対応したタイミングで[recommended-type-checkedにerrorとして追加された](https://github.com/typescript-eslint/typescript-eslint/commit/ae1414c2968b915a4d3a9fa419ce992b378fe2ed#diff-51f2ea270683e4c5db2b2e0e3110b05fd63d65f500a3c22abde76b8f9eb5dcc6)ようです。  
これにより3件のエラーが検出されています。

#### ルール `@typescript-eslint/unbound-method` について

こちらは以前からrecommended-type-checkedにあり、旧コンフィグ時点でerrorとして設定されていたようですが、何故か検出されていませんでした。  
今回、2件のエラーが新たに検出されるようになっています。

#### `Unused eslint-disable directive` 警告について

v9から、 `eslint-disable` 系のルール無効化コメントが不要な場合に[デフォルトで警告が出るようになった](https://github.com/eslint/eslint/commit/24ce9276d472b85541c4b01db488c789f33fd234)ようです。

本来なら警告を出す方が良いと思います。  
しかし、このプロジェクトには開発時はoffでproductionビルド時に警告を出すルールがあり、それを無効化するコメントが入っています。(no-console等)  
このルールが開発時に不要だとして警告を出し続けてしまうため、切っておく方が良さそうです。

#### 現状の問題点

~~v9に正式対応していないプラグインがそこそこあります。~~
これら全てFlatConfigに対応したようです。

- `@vue/eslint-config-prettier` vuejs/eslint-config-prettier#19
    - FlatCompatで対応可能。
- `@vue/eslint-config-typescript` vuejs/eslint-config-typescript#76
    - バージョン範囲外でインストール不可。  
        一応、 `--force` で強制インストールすればFlatCompatで動きました。
- `eslint-plugin-import` import-js/eslint-plugin-import#2948
    - プラグインとしてなら普通に使えました。
- `eslint-plugin-storybook` storybookjs/eslint-plugin-storybook#157
    - 実行時エラーでおそらく現状使用不可。

## VOICEVOXのバージョン

0.?.0

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

## その他

長々と書きましたが、結論は ~~「FlatConfig未対応プラグインが対応するまで移行不可」です。~~
~~1点を除き、~~ もう十分に移行可能だと思われます。

**Comment by Hiroshiba** [comment]
まとめありがとうございます！！！！！！！！！！
非常に参考になります！！！

結論の「FlatConfig未対応プラグインが対応するまで移行不可」に賛成です！

調べてみた感じ旧仕様のが利用不可になるv10のリリースが2024年末～2025年初頭らしいので･･･え、もうそろそろですね･･･。
将来、旧仕様configが使えるESLint v9がしんどくなってきたら、未対応のルールは切り捨ててでもFlatConfig対応したくなりそうですね･･･。

とりあえず依存ライブラリが対応してくれる、あるいはv10がリリースされるまで待機･･･ですかねぇ･･･。

**Comment by Hiroshiba** [comment]
@MT224244 さんがあげてくださっているeslint v9未対応リスト、もう全部実装状態になっていそう･･･？
ということは移行可能になった･･･？　（まだ未対応なものあるかも？）

**Comment by raa0121** [comment]
私も気になったので、main をマージしてから、npm install が通るまで、いじってみました。
https://github.com/VOICEVOX/voicevox/compare/main...raa0121:voicevox:flat-config
この状態だと、以下のようなエラーになりました。
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './recommended' is not defined by "exports" in C:\msys64\home\raa0121\develop\voicevox\node_modules\@vue\eslint-config-typescript\package.json
Referenced from:
    at exportsNotFound (node:internal/modules/esm/resolve:314:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:662:9)
    at resolveExports (node:internal/modules/cjs/loader:640:36)
    at Function._findPath (node:internal/modules/cjs/loader:748:31)
    at Function._resolveFilename (node:internal/modules/cjs/loader:1235:27)
    at Function.resolve (node:internal/modules/helpers:148:19)
    at Module.resolve (file:///C:/msys64/home/raa0121/develop/voicevox/node_modules/@eslint/eslintrc/lib/shared/relative-module-resolver.js:23:46)
    at ConfigArrayFactory._loadExtendedShareableConfig (file:///C:/msys64/home/raa0121/develop/voicevox/node_modules/@eslint/eslintrc/lib/config-array-factory.js:929:33)
    at ConfigArrayFactory._loadExtends (file:///C:/msys64/home/raa0121/develop/voicevox/node_modules/@eslint/eslintrc/lib/config-array-factory.js:810:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (file:///C:/msys64/home/raa0121/develop/voicevox/node_modules/@eslint/eslintrc/lib/config-array-factory.js:749:25)
```

**Comment by Hiroshiba** [comment]
おーーー！！！

エラー見るに、ちょっとまだ設定しきれてない感ありそうですね！！
エラーは`@vue\eslint-config-typescript`･･･？
config.tsに書かれてなさそうだけど、`compatExtend("@vue/typescript/recommended")`のとこ･･･？

**Comment by raa0121** [comment]
> config.tsに書かれてなさそうだけど、compatExtend("@vue/typescript/recommended")のとこ･･･？難しい！！

そうですね 、そこなんですが、recommended が export されなくなったようです。
公式の設定方法を見ると、
```diff
diff --git a/eslint.config.mjs b/eslint.config.mjs
index 3f8438b7..37b5ce5c 100644
--- a/eslint.config.mjs
+++ b/eslint.config.mjs
@@ -15,6 +15,8 @@ import {
   configs,
   parser as typescriptParser,
 } from "typescript-eslint";
+import pluginVue from "eslint-plugin-vue";
+import vueTsEslintConfig from "@vue/eslint-config-typescript";

 const compat = new FlatCompat();

@@ -135,10 +137,16 @@ export default defineConfig(
     ignores: ["dist_electron/**/*", "dist/**/*", "node_modules/**/*"],
   },

+  ...configs.recommended,
   ...pluginConfig(vueConfigRecommended),
   ...pluginConfig("eslint:recommended", js.configs.recommended),
   ...compatExtend("@vue/prettier"),
-  ...compatExtend("@vue/typescript/recommended"),
+  ...pluginVue.configs["flat/essential"],
+  ...vueTsEslintConfig({
+    extends: [
+      "recommended",
+    ],
+  }),
   ...pluginConfig("prettier:recommended", prettierConfigRecommended),
   ...compatExtend("plugin:@voicevox/all"),
   // ...compatExtends("plugin:storybook/recommended"),
```
のように設定すれば良いっぽいんですが、そうすると今度は以下のようなエラーが出て、ぐぬぬとなります
```
ConfigError: Config "typescript-eslint/base": Key "plugins": Cannot redefine plugin "@typescript-eslint".
    at rethrowConfigError (C:\msys64\home\raa0121\develop\voicevox\node_modules\@eslint\config-array\dist\cjs\index.cjs:303:8)
    at C:\msys64\home\raa0121\develop\voicevox\node_modules\@eslint\config-array\dist\cjs\index.cjs:1098:5
    at Array.reduce (<anonymous>)
    at FlatConfigArray.getConfigWithStatus (C:\msys64\home\raa0121\develop\voicevox\node_modules\@eslint\config-array\dist\cjs\index.cjs:1091:43)
    at FlatConfigArray.getConfig (C:\msys64\home\raa0121\develop\voicevox\node_modules\@eslint\config-array\dist\cjs\index.cjs:1120:15)
    at C:\msys64\home\raa0121\develop\voicevox\node_modules\eslint\lib\eslint\eslint-helpers.js:346:56
    at Array.reduce (<anonymous>)
ESLint: 9.10.064\home\raa0121\develop\voicevox\node_modules\eslint\lib\eslint\eslint-helpers.js:333:36
    at C:\msys64\home\raa0121\develop\voicevox\node_modules\eslint\lib\eslint\eslint-helpers.js:296:32
ConfigError: Config "typescript-eslint/base": Key "plugins": Cannot redefine plugin "@typescript-eslint".readers    at rethrowConfigError (C:\msys64\home\raa0121\develop\voicevox\node_modules\@eslint\config-array\dist\cjs\index.cjs:303:8)
    at C:\msys64\home\raa0121\develop\voicevox\node_modules\@eslint\config-array\dist\cjs\index.cjs:1098:5
    at Array.reduce (<anonymous>)
    at FlatConfigArray.getConfigWithStatus (C:\msys64\home\raa0121\develop\voicevox\node_modules\@eslint\config-array\dist\cjs\index.cjs:1091:43)
    at FlatConfigArray.getConfig (C:\msys64\home\raa0121\develop\voicevox\node_modules\@eslint\config-array\dist\cjs\index.cjs:1120:15)
    at C:\msys64\home\raa0121\develop\voicevox\node_modules\eslint\lib\eslint\eslint-helpers.js:346:56
    at Array.reduce (<anonymous>)
    at C:\msys64\home\raa0121\develop\voicevox\node_modules\eslint\lib\eslint\eslint-helpers.js:333:36
    at C:\msys64\home\raa0121\develop\voicevox\node_modules\eslint\lib\eslint\eslint-helpers.js:296:32
    at Object.isAppliedFilter (C:\msys64\home\raa0121\develop\voicevox\node_modules\@nodelib\fs.walk\out\readers\common.js:12:31)
```

**Comment by Hiroshiba** [comment]
次は`typescript-eslint`でimportしてるconfigsとかが怪しそう･･･？

**Comment by raa0121** [comment]
extends が悪さをしてるようです…
コメントアウトすると、eslint 自体は通りましたが、これでいいかは…
```diff
@@ -146,7 +153,7 @@ export default defineConfig(
   {
     name: "voicevox/type-checked/typescript",
     files: ["*/**/*.ts"],
-    extends: [...configs.recommendedTypeChecked],
+    //extends: [...configs.recommendedTypeChecked],
     languageOptions: {
       parser: typescriptParser,
       parserOptions: {
@@ -161,7 +168,7 @@ export default defineConfig(
   {
     name: "voicevox/type-checked/vue",
     files: ["**/*.vue"],
-    extends: [...configs.recommendedTypeChecked],
+    //extends: [...configs.recommendedTypeChecked],
     languageOptions: {
       parser: vueParser,
       parserOptions: {
```

**Comment by Hiroshiba** [comment]
コメントアウトしてルールが効いてるなら大丈夫かと！（たぶん効いてない気がします）

typescript-eslintのドキュメントにflat configの書き方は書いてない感じですかね？
探してみた感じだと、これ…？（違うかも）
https://typescript-eslint.io/users/configs

**Comment by MT224244** [comment]
5ヶ月前に触ったっきりで色々忘れていて何か抜けている可能性はありますが、とりあえず当時試しに作っていたブランチを更新してみました。
`import/order` を効かせようとすると何故かセグフォで落ちるようになってしまったこと以外、一応正常に動いている気がします。
https://github.com/MT224244/voicevox/tree/flat-config

<details>
<summary>npm run lint</summary>

```
path\to\voicevox\src\backend\electron\manager\engineInfoManager.ts
  238:14  warning  'e' is defined but never used  @typescript-eslint/no-unused-vars

path\to\voicevox\src\backend\electron\manager\windowManager.ts
  123:7  error  Expected an assignment or function call and instead saw an expression  @typescript-eslint/no-unused-expressions

path\to\voicevox\src\components\Dialog\SettingDialog\SettingDialog.vue
  221:19  error  Attribute 'v-model:open-dialog' can't be hyphenated  vue/attribute-hyphenation
  239:19  error  Attribute 'v-model:open-dialog' can't be hyphenated  vue/attribute-hyphenation

path\to\voicevox\src\components\Menu\ContextMenu\Presentation.vue
  41:31  error  Explicit undefined is unnecessary on an optional parameter  @typescript-eslint/no-duplicate-type-constituents

path\to\voicevox\src\components\Talk\AudioCell.vue
  48:7  error  Attribute 'v-model:selected-voice' can't be hyphenated  vue/attribute-hyphenation

path\to\voicevox\src\components\Talk\AudioInfo.vue
   86:27  error  Attribute 'v-model:open-dialog' can't be hyphenated     vue/attribute-hyphenation
  219:11  error  Attribute 'v-model:selected-voice' can't be hyphenated  vue/attribute-hyphenation

path\to\voicevox\tools\generateLicenses.mts
  63:32  error  Replace `⏎··import.meta.dirname,⏎··"..",⏎··"vendored",⏎··"7z",⏎` with `import.meta.dirname,·"..",·"vendored",·"7z"`  prettier/prettier

✖ 9 problems (8 errors, 1 warning)
  7 errors and 0 warnings potentially fixable with the `--fix` option.
```
</details>

**Comment by raa0121** [comment]
eslint --debug . しても、セグフォした原因が出ないの辛いですね…

**Comment by Hiroshiba** [comment]
@MT224244 おーー！！！　だいたい動くのすごい！！！！！！！！

> import/order を効かせようとすると何故かセグフォで落ちるようになってしまった

逆に言えば import/order を一旦コメントアウトすれば動くという感じでしょうか 👀 
であればとりあえずマージを目指しても良いのではとちょっと思いました！！！
かなりメンテナンスしやすくなっていると思うので･･･！！

セグフォで落ちる件ですが、（imoprt/orderとは関係ないかもですが）日本語ファイル名にlintをかけようとすると落ちる現象が発生しています 😇 
https://github.com/VOICEVOX/voicevox/issues/2379
もし同じ現象でしたら、なぜか`node v20`までバージョンを落とすと動くので確かめれるかもです。。（でもこのバージョンだとeslintとかが動かなくなることもありそう）

とりあえず参考になればと思ってコメントしました！！

**Comment by MT224244** [comment]
試しにNodeのバージョンを `v20.18.1` に落として実行してみたところ、`import/order` 込みでもセグフォにならなくなりました…。
ただ、こちらはv21でも通ったのと、`tests` を除外しても変わらないので、ちょっとそのIssueとは違う原因かもしれません。

**Comment by MT224244** [comment]
[こちら](https://httptoolkit.com/blog/how-to-debug-node-segfaults/)にセグフォのログを吐く方法が載っていたので試してみましたが、特に有益そうな情報は含まれていなさそうでした…。

<details>
<summary>ログ</summary>

```
PID 50260 received SIGSEGV for address: 0x15227e00
SymInit: Symbol-SearchPath: '.;path\to\voicevox;C:\Users\***\AppData\Local\Volta\tools\image\node\22.11.0;C:\WINDOWS;C:\WINDOWS\system32;SRV*C:\websymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 530, UserName: '***'
OS-Version: 10.0.26100 () 0x100-0x1
path\to\voicevox\node_modules\segfault-handler\src\StackWalker.cpp (941): StackWalker::ShowCallstack
path\to\voicevox\node_modules\segfault-handler\src\segfault-handler.cpp (242): segfault_handler
00007FFAF3DBED36 (ntdll): (filename not available): RtlWow64GetCurrentCpuArea
00007FFAF3DBF13E (ntdll): (filename not available): RtlWow64GetCurrentCpuArea
00007FFAF3F0379E (ntdll): (filename not available): KiUserExceptionDispatcher
00007FF715227E00 (node): (filename not available): v8::MeasureMemoryDelegate::`vftable'
00007FF71098E610 (node): (filename not available): uv_setup_args
00007FF710B3005F (node): (filename not available): v8::CTypeInfoBuilder<v8::FastOneByteString const & __ptr64>::Build
00007FF710B2681F (node): (filename not available): v8::CTypeInfoBuilder<v8::FastOneByteString const & __ptr64>::Build
00007FF710BBC398 (node): (filename not available): X509_STORE_get_cleanup
00007FF6B178FBC7 ((module-name not available)): (filename not available): (function-name not available)
000000F6F73FDCD0 ((module-name not available)): (filename not available): (function-name not available)
0000027B1AB01231 ((module-name not available)): (filename not available): (function-name not available)
000000F6F73FDCE8 ((module-name not available)): (filename not available): (function-name not available)
00000103684C0069 ((module-name not available)): (filename not available): (function-name not available)
000000F6F73FDCB0 ((module-name not available)): (filename not available): (function-name not available)
000000F6F73FDCE8 ((module-name not available)): (filename not available): (function-name not available)
0000000000000001 ((module-name not available)): (filename not available): (function-name not available)
0000000000000040 ((module-name not available)): (filename not available): (function-name not available)
000000F6F73FDC50 ((module-name not available)): (filename not available): (function-name not available)
0000000000000006 ((module-name not available)): (filename not available): (function-name not available)
000000F6F73FDD48 ((module-name not available)): (filename not available): (function-name not available)
00007FF691B88D1A ((module-name not available)): (filename not available): (function-name not available)
0000027B1AB1DAD1 ((module-name not available)): (filename not available): (function-name not available)
000002800D0A5000 ((module-name not available)): (filename not available): (function-name not available)
```
</details>

**Comment by MT224244** [comment]
#2379 でも触れられていますが、日本語がダメというより特定の文字がダメという感じのようです。
ファイル名やフォルダ名からいくつかの文字を消すと正常に通るようになりました。

![Image](https://github.com/user-attachments/assets/d7862a41-644e-4d30-b4ee-ef6488003377)

参考までに、以下が削除した文字のリストです。

ファイル名
`え` `き` `ツ` `ッ` `テ` `デ` `ト` `バ` `プ` `加` `択`

フォルダ名
`複`

`択` はファイル名にもフォルダ名にも存在しますが、ファイル名だけダメなようです。

**Comment by MT224244** [comment]
> 逆に言えば import/order を一旦コメントアウトすれば動くという感じでしょうか 👀
であればとりあえずマージを目指しても良いのではとちょっと思いました！！！
かなりメンテナンスしやすくなっていると思うので･･･！！

この点について回答し忘れていました。
私個人のスタンスとしては、 #2379 が閉じられるまではこのまま様子見でいいのではと思っています。

**Comment by Hiroshiba** [comment]
詳細な調査感謝です！！！！！

> ファイル名
`え` `き` `ツ` `ッ` `テ` `デ` `ト` `バ` `プ` `加` `択`

････････････！？！？
`ト`とか`ッ`とかは、他のファイル名にも含まれてますね！！！
`ア_プデート通知ダイアログ`とか`スクリーンショッ_`とか！！

謎！！！！！！

---

> 私個人のスタンスとしては、 https://github.com/VOICEVOX/voicevox/issues/2379 が閉じられるまではこのまま様子見でいいのではと思っています。

こちら承知しました！　たしかにせっかくなので全部実装しちゃいたいですね！！

たぶん僕たちで解決は困難＆待っていても解決しない（node21からずっとだから）ので、こちらからeslintに報告するのが良いかなぁと思ってます 🙏 
再現できる最小構成をgithub上に作って、eslint辺りにissueを作るとか、再現できるコードをzipにまとめてissueに添付するとか。
（逆に言うとこれで一気に進みそうな気がします）

ただもしかしたらgit cloneした段階で文字コードが変わってエラーが再現しなくなる、みたいなのもあり得るかもなんですよねぇ。
ファイル名を形成してる文字の詳しい情報とか調べてみると条件がなにかわかるかもですが･･･。

ちょっとまとまってないけどコメントまで 🙇

**Comment by MT224244** [comment]
> `ト`とか`ッ`とかは、他のファイル名にも含まれてますね！！！
`ア_プデート通知ダイアログ`とか`スクリーンショッ_`とか！！

あれ…？確かに、気づきませんでした…。

実は1文字ずつファイルを作って(`あ.ts`みたいな)読み込ませて検証した表もあったんですが、実際にあるファイルと照らすと違うことがあったので貼るのをやめたんですよね…。
文字毎の条件の他に、文字の組み合わせ等の条件も絡んでいるのかもしれません。

赤=セグフォ
![Image](https://github.com/user-attachments/assets/5e8cf122-0cdf-4439-9bd8-abcba6fd21c9)

**Comment by Yosshi999** [comment]
連続箇所が32文字なのは何か意味があるんですかね...?

**Comment by MT224244** [comment]
Discordを見ていてファイル名の文字コードについての話があったので調べてみると、現在のデフォルトはsjisですが、Win11ではutf8に変更することができるようです。
https://www.momopoem.com/?p=919
![Image](https://github.com/user-attachments/assets/56174bba-93bb-4866-a370-5961ef99685d)

試しにやってみたところ、元のファイル名でもlintが通りました。

**Comment by Hiroshiba** [comment]
なるほどです！！　ということはsjisが原因説が濃厚そう･･･。
そのutf8に変える機能、結構いろんなソフトウェアが不具合を出すらしいのと、新規コミッターが混乱しそうなんですよね･･･ 😇

**Comment by MT224244** [comment]
あくまで検証でオンにしましたが、この設定のままにはしたくないですね…。
原因の特定に繋がる手がかりの一つになると思って報告しただけで、私もこれを解決法とするつもりはないです😇

**Comment by takejohn** [comment]
最小再現例作ってみました
https://github.com/takejohn/voicevox/tree/repro/eslint-plugin-import-filename-issue
`npm run fmt`でSegmentation faultになります。
`あ.ts`のファイル名を変更するとセグフォったりセグフォらなかったり……

**Comment by Hiroshiba** [comment]
ありがとうございます！！
`import path from "path";`が書かれてる`あ.ts`があるだけ･･･！！！！

とりあえず他にも困ってる方がいるかもなので、eslint側に報告してあげたいですね。
eslintレベルになると向こうの体裁用に整えるのちょっと大変かもですが、もしよかったら･･･！ @takejohn 
（あんま乗り気じゃなければ僕からやっておきます！！）

あとちゃんとimport周りのこと知らないのですが、もしかしたら`node:path`をimportするとセグフォしなかったりするのでしょうか。

**Comment by takejohn** [comment]
> あとちゃんとimport周りのこと知らないのですが、もしかしたら`node:path`をimportするとセグフォしなかったりするのでしょうか。

import文があることが問題のようで、`node:path`に変更しても変わりませんね。

issue報告はしたいと思いますが、eslintよりもeslint-plugin-importの問題な気がします。

**Comment by Hiroshiba** [comment]
なーーーーーーるほどです！！！

> issue報告はしたいと思いますが、eslintよりもeslint-plugin-importの問題な気がします。

これそういえば`fmt`（つまり`--fix`付き）はセグフォになるけど、そうじゃない場合はセグフォにならなかったと思います！
もしこの再現でもそうなら、eslintのfix側の実装が課題の可能性が高まるかも･･･？

**Comment by takejohn** [comment]
> これそういえば`fmt`（つまり`--fix`付き）はセグフォになるけど、そうじゃない場合はセグフォにならなかったと思います！ もしこの再現でもそうなら、eslintのfix側の実装が課題の可能性が高まるかも･･･？

`--fix` フラグを省いてもセグフォのようです。

**Comment by Hiroshiba** [comment]
なるほどです！！　ちょっと手元で試した感じ、今のVOICEVOXのmainブランチでも同じ挙動でした 🙇 🙇 🙇

**Comment by Hiroshiba** [comment]
@MT224244 https://github.com/VOICEVOX/voicevox/issues/2379 が解決されたのでご連絡です！！ 🚀
