### ISSUE TITLE
engine 0.9.1のopenapi.jsonを使ってopenapi-generator-cli generateするとエラーが出る

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#513]
## 不具合の内容

バージョン0.9.1のengineからopenapi.jsonwを取得してapiを生成しようとするとエラーが表示されました。

### 現象・ログ

```bash
Download 5.1.1 ...
Downloaded 5.1.1
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 1, Warning count: 0
Errors:
        -attribute components.schemas.SpeakerInfo.default is not of type `array`

        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:546)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:573)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:433)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

## VOICEVOXのバージョン

0.?.0

## その他

例外的になってしまいますが、0.9.1ではopenapi.jsonを更新しないことにしました。

**Comment by y-chan** [comment]
多分 VOICEVOX/voicevox_engine#240 で修正されたので、closeします
