### ISSUE TITLE
【アナウンス】.envのDEFAULT_ENGINE_INFOSのkeyキーはuuidキーにリネームされました

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#882]
- https://github.com/VOICEVOX/voicevox/pull/871

の変更で、engine key→engine uuidとなった関係で、リネームが入りました。
これをリネームしていない場合、`Error: No such engine registered: index == 0`エラーが発生します。

```bash
[00:39:19.957] [error] Error: No such engine registered: index == 0
    at _callee6$ (http://localhost:8080/js/webpack:/src/store/audio.ts:569:15)
    at tryCatch (http://localhost:8080/js/webpack:/node_modules/regenerator-runtime/runtime.js:63:15)
    at Generator.invoke [as _invoke] (http://localhost:8080/js/webpack:/node_modules/regenerator-runtime/runtime.js:293:1)
    at Generator.next (http://localhost:8080/js/webpack:/node_modules/regenerator-runtime/runtime.js:118:1)
    at http://localhost:8080/js/webpack:/node_modules/tslib/tslib.es6.js:74:1
    at new Promise (<anonymous>)
    at __awaiter (http://localhost:8080/js/webpack:/node_modules/tslib/tslib.es6.js:70:1)
    at http://localhost:8080/js/webpack:/src/store/audio.ts:566:78
    at Store.<anonymous> (http://localhost:8080/js/webpack:/src/store/ui.ts:24:12)
    at Array.wrappedActionHandler (http://localhost:8080/js/webpack:/node_modules/vuex/dist/vuex.esm-browser.js:815:1)
```

こんな感じでキーを変えてください。

https://github.com/VOICEVOX/voicevox/commit/b35ddc8a248b71459046ed72a499314b9a0396d6#diff-48f73ea2653e45c41f31afc2d42dfde14d8caf26d8dd24d3d2a81a52604f4cb6

**Comment by Hiroshiba** [comment]
１ヶ月経過したのでpinnedを外し、closeしたいと思います。
