### ISSUE TITLE
最新版のmainで、「エンジン起動中」が終わらないことがある

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox#940]
## 不具合の内容

タイトルの通りです。

### 現象・ログ

```bash
(node:18624) ExtensionLoadWarning: Warnings loading extension at C:\Users\hihok\AppData\Roaming\voicevox-dev\extensions\ljjemllljcmogpfapbkkighbhhppjdbg:
  Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
  Permission 'contextMenus' is unknown or URL pattern is malformed.

(Use `electron --trace-warnings ...` to show where the warning was created)
[01:11:38.607] [info]  Starting 1 engine/s...
[01:11:38.609] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d: Start launching
[01:11:38.610] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d: Starting process
[01:11:38.611] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d mode: GPU
[01:11:38.612] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d path: C:\Users\hihok\Github\voicevox_engine\hiho_release\run.exe
[01:11:38.612] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d args: ["--use_gpu"]
[18624:0917/011138.861:ERROR:CONSOLE(1)] "TypeError: Failed to fetch", source: devtools://devtools/bundled/entrypoints/main/main.js (1)
[18624:0917/011139.166:ERROR:CONSOLE(160)] "Electron sandbox_bundle.js script failed to run", source: node:electron/js2c/sandbox_bundle (160)
[18624:0917/011139.166:ERROR:CONSOLE(160)] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: node:electron/js2c/sandbox_bundle (160)
[01:11:41.050] [error] TypeError: Failed to fetch
    at DefaultApi._callee$ (http://localhost:8080/js/webpack:/src/openapi/runtime.ts:89:30)
    at tryCatch (http://localhost:8080/js/webpack:/node_modules/regenerator-runtime/runtime.js:63:15)
    at Generator.invoke [as _invoke] (http://localhost:8080/js/webpack:/node_modules/regenerator-runtime/runtime.js:293:1)      
    at Generator.next (http://localhost:8080/js/webpack:/node_modules/regenerator-runtime/runtime.js:118:1)
    at http://localhost:8080/js/webpack:/node_modules/tslib/tslib.es6.js:74:1
    at new Promise (<anonymous>)
    at __awaiter (http://localhost:8080/js/webpack:/node_modules/tslib/tslib.es6.js:70:1)
    at DefaultApi.BaseAPI.fetchApi (http://localhost:8080/js/webpack:/src/openapi/runtime.ts:79:65)
    at DefaultApi._callee2$ (http://localhost:8080/js/webpack:/src/openapi/runtime.ts:49:37)
    at tryCatch (http://localhost:8080/js/webpack:/node_modules/regenerator-runtime/runtime.js:63:15)
[01:11:42.576] [error] ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDERR: Warning: cpu_num_threads is set to 0. ( The library leaves the decision to the synthesis runtime )

[01:11:42.582] [error] ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDERR: INFO:     Started server process [17376]
INFO:     Waiting for application startup.

[01:11:42.595] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDOUT: reading C:\Users\hihok\Github\voicevox_engine\hiho_release\default.csv ... 42
emitting double-array:  80% |##################################         |
[01:11:42.596] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDOUT: emitting double-array:  83% |########################emitting double-array: 100% |###########################################|

[01:11:42.609] [error] ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDERR: INFO:     Application startup complete.

[01:11:42.610] [error] ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDERR: INFO:     Uvicorn running on http://127.0.0.1:50021 (Press CTRL+C to quit)
```

### 再現手順

PCをスリープから戻して最初に実行したときだけ起こる印象があります。

### 期待動作

毎回接続に成功する

## VOICEVOXのバージョン

b14c4600331f71588e012562ea01108c8c53b701

## OSの種類/ディストリ/バージョン

- [x] Windows
- [ ] macOS
- [ ] Linux

## その他

エンジン（run.exe）はちゃんと起動しているので、不思議です。
![image](https://user-images.githubusercontent.com/4987327/190683846-74626cbd-63d7-423a-a02e-8f01a5d833cf.png)

原因はまだわかっていないのですが、なんとなくエンジン起動のタイミングと何かのAPIを叩くタイミングが初回起動かどうかでずれてるのかなと思っています。
デバッグがしづらいのですが、なにかいい方法ないでしょうか。

**Comment by sevenc-nanashi** [comment]
> ```
> "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))"
> ```

engine_manifestのsupported_featuresとか、ArrayであるべきところがArrayじゃないときにそのエラーが出た覚えがあります。

**Comment by Hiroshiba** [comment]
なるほどです！
なんかちゃんと起動するときと起動しない時があるのでsupported_features部分ではなさそうですが、何かしらのArray部分がnullになっているからというのはほぼ間違いなさそうに思います。

どこだろう･･･engine_infos･･･？

**Comment by sabonerune** [comment]
自分の環境でも似たようなエラーが出ました。

エディタのDevToolのコンソールに
`127.0.0.1:50021/engine_manifest:1          Failed to load resource: net::ERR_CONNECTION_REFUSED`
と出ていたのでエンジン起動完了前にFetchされているのではと予測して
https://github.com/VOICEVOX/voicevox/blob/b801acbeeb061d787f15c56b721e2c2e2b356337/src/openapi/runtime.ts#L89
の前に適当に`await new Promise(resolve => setTimeout(resolve, 5000))`で止めてみたらエラーは出なくなりました。

ヒホさんのログはエラーが出た後にエンジンの起動ログが出ているので同じ問題かもしれません。

(自分の環境の場合Uvicornのログが出てから9ミリ秒後にエラーが出ていますが)

**Comment by sabonerune** [comment]
一番の問題はリトライもせず、エラーも出さずに止まったままという点かもしれません。

**Comment by Hiroshiba** [comment]
なるほどです、ありがとうございます！！

一番良いのは、エンジン側で準備ができたことを知らせるメッセージを発行し、エディタ側はそれを待つことだと思うのですが、まあちょっと大変そうですね･･･。

どこかにリトライ機構を埋め込むのが良いのかなと思いました！
といっても全部に埋め込むのは変な影響出そうなので、起動時にエンジンから情報取得してくる周りだけリトライさせるとかが良い塩梅かもですね！

**Comment by sabonerune** [comment]
@Hiroshiba 
この問題、結構危険な感じがします。
そもそも今までこの問題が発生しなかったのは`START_WAITING_ENGINE_ALL`に元々リトライ処理が実装されていたからのようです。
https://github.com/VOICEVOX/voicevox/blob/32914eb7a20ab039df0f91e6c10e02bf929373ab/src/views/Home.vue#L472-L474
https://github.com/VOICEVOX/voicevox/blob/32914eb7a20ab039df0f91e6c10e02bf929373ab/src/store/audio.ts#L265
しかし、`store.dispatch("START_WAITING_ENGINE_ALL");`の前に`store.dispatch("FETCH_AND_SET_ENGINE_MANIFESTS");`が追加されたことで例外が発生しまったようです。

これがリリースされるとスペックが低い環境だとVOICEVOXが起動できなくなる可能性があると思います。

**Comment by sevenc-nanashi** [comment]
なるほど。
となると`FETCH_AND_SET_ENGINE_MANIFESTS`を`START_WAITING_ENGINE_ALL`の後に持ってくるべきなんですかね？

**Comment by sabonerune** [comment]
ちょっとそこまではVOICEVOXについて理解できていないので分からないです。
ただ、`START_WAITING_ENGINE_ALL`の後ならほぼ間違いなくエンジンは起動しているはずです。

**Comment by sevenc-nanashi** [comment]
ローカルで試してみました。
FETCH_AND_SET_ENGINE_MANIFESTSをSTART_WAITING_ENGINE_ALLの後に持ってきたらバグ無く動作しました。
修正PR出します

**Comment by sabonerune** [comment]
基本的にはOKだと思いますが`Home.vue`の`onMounted()`で例外が発生すると「エンジン起動中」・「データ準備中」の表示で止まってしまうため後々エラー処理の確認をした方がいい気がします。
(エンジンのプロセスは生きているがエンジンが上手く動いていない時くらいしか発生しませんが。)

**Comment by Hiroshiba** [comment]
@sabonerune さんが発見してくださっていたんですね！ありがとうございます！！

起動シーケンスでのエラーハンドリングが甘いのはおっしゃる通りだと思います。
少なくともエラーダイアログが出る形は目指したいところです。
お願いしてしまってすみません、issueを作成をお願いしても良いでしょうか 👀
